[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput --clear']

[start]
cmd = 'gunicorn pneumonia_diagnosis.wsgi --bind 0.0.0.0:$PORT --timeout 120 --workers 2'
